# Generated by Django 3.2.6 on 2021-08-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
